import { Nursery, SeedlingBatch, SeedlingType } from './types.js';

// Example nurseries for the demo. Names, people and phone numbers are fictional.

const batch = (
  id: string,
  speciesId: string,
  seedlingType: SeedlingType,
  ageMonths: number,
  heightCm: number,
  unitPriceUGX: number,
  quantityAvailable: number,
  status: SeedlingBatch['status'] = 'Ready'
): SeedlingBatch => ({ id, speciesId, seedlingType, ageMonths, heightCm, unitPriceUGX, quantityAvailable, status });

export const NURSERIES: Nursery[] = [
  {
    id: 'kasangalabi',
    name: 'Kasangalabi Tree Nursery',
    operatorName: 'Ronald Ssemakula',
    phone: '+256 700 100 101',
    district: 'Mukono',
    subCounty: 'Nama',
    village: 'Kasangalabi',
    region: 'Central',
    coordinates: [0.3942, 32.7638],
    registration: 'NFA registered',
    registrationNumber: 'NFA/NUR/2016/0142',
    established: 2012,
    description: 'Large woodlot nursery supplying eucalyptus, pine and musizi to farmers and schools across central Uganda.',
    deliveryMethods: ['Collect from nursery', 'Boda boda', 'Truck'],
    openingHours: 'Mon–Sat, 7:30am–5:30pm',
    batches: [
      batch('kas-euc', 'eucalyptus', 'Root trainer', 3, 30, 400, 85000),
      batch('kas-pine', 'pine', 'Potted seedling', 6, 25, 500, 40000),
      batch('kas-musizi', 'musizi', 'Potted seedling', 5, 40, 900, 12000),
      batch('kas-grev', 'grevillea', 'Potted seedling', 5, 35, 700, 9500),
    ],
  },
  {
    id: 'seeta-fruit',
    name: 'Seeta Fruit & Tree Seedlings',
    operatorName: 'Sarah Nakato',
    phone: '+256 700 100 102',
    district: 'Mukono',
    subCounty: 'Goma',
    village: 'Seeta',
    region: 'Central',
    coordinates: [0.3610, 32.6960],
    registration: 'MAAIF certified',
    registrationNumber: 'MAAIF/PM/2020/0381',
    established: 2018,
    description: 'Grafted fruit trees from certified mother trees, plus Mutuba cuttings for coffee farmers.',
    deliveryMethods: ['Collect from nursery', 'Boda boda'],
    openingHours: 'Mon–Sat, 8:00am–6:00pm',
    batches: [
      batch('sfs-avo', 'avocado', 'Grafted', 8, 60, 6000, 2400),
      batch('sfs-mango', 'mango', 'Grafted', 9, 55, 5000, 1800),
      batch('sfs-jack', 'jackfruit', 'Potted seedling', 6, 45, 2500, 900),
      batch('sfs-mutuba', 'mutuba', 'Cutting', 2, 120, 1500, 600),
    ],
  },
  {
    id: 'kakiri-community',
    name: 'Kakiri Women Tree Growers',
    operatorName: 'Grace Nalubega',
    phone: '+256 700 100 103',
    district: 'Wakiso',
    subCounty: 'Kakiri',
    village: 'Kakiri Town Council',
    region: 'Central',
    coordinates: [0.4103, 32.3889],
    registration: 'Community group',
    registrationNumber: 'WKS/CBO/2019/0217',
    established: 2019,
    description: 'Women’s group nursery raising native trees for restoration projects and home compounds.',
    deliveryMethods: ['Collect from nursery', 'Boda boda'],
    openingHours: 'Mon–Fri, 8:00am–4:00pm',
    batches: [
      batch('kak-mvule', 'mvule', 'Potted seedling', 8, 45, 2000, 3500),
      batch('kak-nsambya', 'nsambya', 'Potted seedling', 6, 40, 800, 5000),
      batch('kak-mukebu', 'mukebu', 'Potted seedling', 6, 35, 1000, 2800),
      batch('kak-musizi', 'musizi', 'Potted seedling', 4, 30, 800, 4200),
    ],
  },
  {
    id: 'nyendo-agroforestry',
    name: 'Nyendo Agroforestry Nursery',
    operatorName: 'Joseph Kiwanuka',
    phone: '+256 700 100 104',
    district: 'Masaka',
    subCounty: 'Nyendo-Mukungwe',
    village: 'Nyendo',
    region: 'Central',
    coordinates: [-0.3350, 31.7520],
    registration: 'District registered',
    registrationNumber: 'MSK/FOR/2017/044',
    established: 2015,
    description: 'Shade and fruit trees for coffee and banana farmers in greater Masaka.',
    deliveryMethods: ['Collect from nursery', 'Boda boda', 'Truck'],
    openingHours: 'Mon–Sat, 8:00am–5:00pm',
    batches: [
      batch('nye-musizi', 'musizi', 'Potted seedling', 5, 40, 900, 7000),
      batch('nye-grev', 'grevillea', 'Potted seedling', 5, 35, 700, 6500),
      batch('nye-jack', 'jackfruit', 'Potted seedling', 6, 45, 2000, 1200),
      batch('nye-mutuba', 'mutuba', 'Cutting', 2, 120, 1200, 800),
    ],
  },
  {
    id: 'rwizi-valley',
    name: 'Rwizi Valley Seedlings',
    operatorName: 'Brian Tumwesigye',
    phone: '+256 700 100 105',
    district: 'Mbarara',
    subCounty: 'Biharwe',
    village: 'Biharwe',
    region: 'Western',
    coordinates: [-0.5720, 30.7280],
    registration: 'NFA registered',
    registrationNumber: 'NFA/NUR/2018/0266',
    established: 2014,
    description: 'Woodlot and fruit seedlings for farmers in Ankole, with truck delivery for large orders.',
    deliveryMethods: ['Collect from nursery', 'Boda boda', 'Truck'],
    openingHours: 'Mon–Sat, 7:30am–5:00pm',
    batches: [
      batch('rwz-euc', 'eucalyptus', 'Root trainer', 3, 30, 350, 60000),
      batch('rwz-pine', 'pine', 'Potted seedling', 6, 25, 500, 25000),
      batch('rwz-grev', 'grevillea', 'Potted seedling', 5, 35, 700, 8000),
      batch('rwz-avo', 'avocado', 'Grafted', 8, 55, 6500, 1500),
    ],
  },
  {
    id: 'rwenzori-highlands',
    name: 'Rwenzori Highlands Tree Nursery',
    operatorName: 'Esther Kabasinguzi',
    phone: '+256 700 100 106',
    district: 'Kabarole',
    subCounty: 'Karambi',
    village: 'Kasusu',
    region: 'Western',
    coordinates: [0.6590, 30.2680],
    registration: 'District registered',
    registrationNumber: 'KBR/FOR/2019/031',
    established: 2016,
    description: 'Highland species for tea and coffee farms on the Rwenzori foothills.',
    deliveryMethods: ['Collect from nursery', 'Boda boda'],
    openingHours: 'Mon–Sat, 8:00am–5:00pm',
    batches: [
      batch('rwn-prunus', 'prunus', 'Potted seedling', 8, 40, 2000, 3000),
      batch('rwn-grev', 'grevillea', 'Potted seedling', 5, 35, 700, 7500),
      batch('rwn-mahog', 'mahogany', 'Potted seedling', 9, 45, 1800, 1200),
      batch('rwn-euc', 'eucalyptus', 'Root trainer', 3, 30, 400, 20000),
    ],
  },
  {
    id: 'bunyoro-growers',
    name: 'Bunyoro Tree Growers’ Nursery',
    operatorName: 'Moses Byaruhanga',
    phone: '+256 700 100 107',
    district: 'Hoima',
    subCounty: 'Bugambe',
    village: 'Bugambe',
    region: 'Western',
    coordinates: [1.3730, 31.2860],
    registration: 'NFA registered',
    registrationNumber: 'NFA/NUR/2017/0198',
    established: 2013,
    description: 'Native hardwoods for restoring forest edges around Bugoma and Budongo, plus pine for plantations.',
    deliveryMethods: ['Collect from nursery', 'Truck'],
    openingHours: 'Mon–Fri, 8:00am–5:00pm',
    batches: [
      batch('bny-mahog', 'mahogany', 'Potted seedling', 9, 45, 1500, 4000),
      batch('bny-mvule', 'mvule', 'Potted seedling', 8, 45, 1800, 3000),
      batch('bny-musizi', 'musizi', 'Potted seedling', 5, 40, 800, 6000),
      batch('bny-pine', 'pine', 'Potted seedling', 6, 25, 450, 30000),
    ],
  },
  {
    id: 'laroo-farmers',
    name: 'Laroo Farmers’ Tree Nursery',
    operatorName: 'Denis Okello',
    phone: '+256 700 100 108',
    district: 'Gulu',
    subCounty: 'Laroo',
    village: 'Laroo',
    region: 'Northern',
    coordinates: [2.7600, 32.3150],
    registration: 'Community group',
    registrationNumber: 'GUL/CBO/2018/0093',
    established: 2017,
    description: 'Farmer-run nursery raising shea, mango and woodlot trees for Acholi sub-region.',
    deliveryMethods: ['Collect from nursery', 'Boda boda'],
    openingHours: 'Mon–Sat, 8:00am–5:00pm',
    batches: [
      batch('lar-shea', 'shea', 'Potted seedling', 10, 30, 2500, 1500),
      batch('lar-mango', 'mango', 'Grafted', 9, 50, 4500, 1200),
      batch('lar-mvule', 'mvule', 'Potted seedling', 8, 40, 1800, 1000, 'Ready soon'),
      batch('lar-euc', 'eucalyptus', 'Root trainer', 3, 30, 350, 15000),
    ],
  },
  {
    id: 'lira-fruit',
    name: 'Lira Fruit Tree Centre',
    operatorName: 'Harriet Apio',
    phone: '+256 700 100 109',
    district: 'Lira',
    subCounty: 'Adekokwok',
    village: 'Adekokwok',
    region: 'Northern',
    coordinates: [2.2400, 32.9500],
    registration: 'MAAIF certified',
    registrationNumber: 'MAAIF/PM/2019/0254',
    established: 2016,
    description: 'Certified grafted mango and fruit seedlings for Lango farmers and juice processors.',
    deliveryMethods: ['Collect from nursery', 'Boda boda', 'Truck'],
    openingHours: 'Mon–Sat, 8:00am–5:30pm',
    batches: [
      batch('lir-mango', 'mango', 'Grafted', 9, 55, 4500, 3500),
      batch('lir-jack', 'jackfruit', 'Potted seedling', 6, 40, 2000, 1000),
      batch('lir-shea', 'shea', 'Potted seedling', 10, 30, 2500, 800),
      batch('lir-avo', 'avocado', 'Grafted', 8, 50, 6000, 400, 'Ready soon'),
    ],
  },
  {
    id: 'elgon-shade',
    name: 'Elgon Coffee Shade Nursery',
    operatorName: 'Isaac Wanyera',
    phone: '+256 700 100 110',
    district: 'Mbale',
    subCounty: 'Bungokho',
    village: 'Bungokho',
    region: 'Eastern',
    coordinates: [1.0600, 34.2300],
    registration: 'District registered',
    registrationNumber: 'MBL/FOR/2018/057',
    established: 2011,
    description: 'Shade and soil-protection trees for Arabica coffee farmers on the slopes of Mt Elgon.',
    deliveryMethods: ['Collect from nursery', 'Boda boda'],
    openingHours: 'Mon–Sat, 7:30am–5:00pm',
    batches: [
      batch('elg-grev', 'grevillea', 'Potted seedling', 5, 35, 600, 12000),
      batch('elg-mukebu', 'mukebu', 'Potted seedling', 6, 35, 1000, 3500),
      batch('elg-prunus', 'prunus', 'Potted seedling', 8, 40, 2000, 2000),
      batch('elg-avo', 'avocado', 'Grafted', 8, 55, 6000, 900),
    ],
  },
  {
    id: 'west-nile',
    name: 'West Nile Tree Nursery',
    operatorName: 'Jimmy Drani',
    phone: '+256 700 100 111',
    district: 'Arua',
    subCounty: 'Ayivu',
    village: 'Ayivu',
    region: 'Northern',
    coordinates: [3.0350, 30.9400],
    registration: 'Community group',
    registrationNumber: 'ARU/CBO/2020/0121',
    established: 2020,
    description: 'Fruit and woodlot seedlings for households and refugee-hosting communities in West Nile.',
    deliveryMethods: ['Collect from nursery', 'Boda boda'],
    openingHours: 'Mon–Sat, 8:00am–5:00pm',
    batches: [
      batch('wnl-mango', 'mango', 'Grafted', 9, 50, 4500, 1500),
      batch('wnl-euc', 'eucalyptus', 'Root trainer', 3, 30, 350, 18000),
      batch('wnl-mvule', 'mvule', 'Potted seedling', 8, 40, 1800, 800),
      batch('wnl-shea', 'shea', 'Potted seedling', 10, 30, 2500, 600),
    ],
  },
  {
    id: 'kigezi-highland',
    name: 'Kigezi Highland Seedlings',
    operatorName: 'Annet Ainembabazi',
    phone: '+256 700 100 112',
    district: 'Kabale',
    subCounty: 'Kitumba',
    village: 'Kitumba',
    region: 'Western',
    coordinates: [-1.2700, 29.9800],
    registration: 'NFA registered',
    registrationNumber: 'NFA/NUR/2015/0087',
    established: 2010,
    description: 'Highland woodlot and soil-conservation trees for the steep hills of Kigezi.',
    deliveryMethods: ['Collect from nursery', 'Boda boda', 'Truck'],
    openingHours: 'Mon–Sat, 7:30am–5:00pm',
    batches: [
      batch('kig-euc', 'eucalyptus', 'Root trainer', 3, 30, 400, 45000),
      batch('kig-grev', 'grevillea', 'Potted seedling', 5, 35, 600, 15000),
      batch('kig-prunus', 'prunus', 'Potted seedling', 8, 40, 2000, 2500),
      batch('kig-avo', 'avocado', 'Grafted', 8, 55, 6500, 700),
    ],
  },
];
