import { SeedlingProgramme } from './types.js';

// Example programmes for the demo. Sponsors are fictional.
export const PROGRAMMES: SeedlingProgramme[] = [
  {
    id: 'victoria-catchment',
    title: 'Lake Victoria Catchment Restoration',
    sponsorName: 'Victoria Basin Trees Trust',
    sponsorType: 'NGO',
    description: 'Free native seedlings for households and farmer groups planting along streams, wetland edges and degraded hillsides draining into Lake Victoria.',
    districts: ['Mukono', 'Wakiso', 'Masaka', 'Buikwe'],
    speciesIds: ['mvule', 'musizi', 'nsambya', 'mutuba'],
    maxPerApplicant: 200,
    totalSeedlings: 60000,
    seedlingsClaimed: 41200,
    requirements: [
      'Land in one of the listed districts (at least a quarter acre)',
      'Introduction letter from your LC1 chairperson',
      'Agree to a follow-up visit six months after planting',
    ],
    deadline: '2026-10-31',
    status: 'Open',
    collectionNurseryIds: ['kakiri-community', 'nyendo-agroforestry', 'kasangalabi'],
  },
  {
    id: 'northern-shea-fruit',
    title: 'Shea & Fruit Trees for Northern Uganda',
    sponsorName: 'Acholi–Lango Livelihoods Initiative',
    sponsorType: 'NGO',
    description: 'Supports women’s groups and smallholders to plant shea and grafted mango for income, and to replace trees cut for charcoal.',
    districts: ['Gulu', 'Nwoya', 'Lira'],
    speciesIds: ['shea', 'mango'],
    maxPerApplicant: 50,
    totalSeedlings: 20000,
    seedlingsClaimed: 8600,
    requirements: [
      'Member of a registered farmer or women’s group',
      'Consent from the family or clan for the land to be planted',
      'Attend a one-day tree care training at the collection nursery',
    ],
    deadline: '2026-11-15',
    status: 'Open',
    collectionNurseryIds: ['laroo-farmers', 'lira-fruit'],
  },
  {
    id: 'green-schools',
    title: 'Green Schools Programme',
    sponsorName: 'Mpanga Millers Foundation',
    sponsorType: 'Company',
    description: 'Fruit and shade trees for primary and secondary school compounds, with a pupils’ tree club to look after them.',
    districts: [],
    speciesIds: ['jackfruit', 'mango', 'avocado', 'nsambya'],
    maxPerApplicant: 100,
    totalSeedlings: 15000,
    seedlingsClaimed: 11800,
    requirements: [
      'Application made by the head teacher or deputy',
      'A named teacher responsible for the school tree club',
      'Space on the school compound protected from livestock',
    ],
    deadline: '2026-12-05',
    status: 'Open',
    collectionNurseryIds: ['seeta-fruit', 'lira-fruit', 'rwizi-valley'],
  },
  {
    id: 'elgon-slopes',
    title: 'Elgon Slopes Soil Protection',
    sponsorName: 'Elgon Hillside Farmers’ Network',
    sponsorType: 'Community organisation',
    description: 'Trees for contour planting on steep coffee farms to reduce soil loss and landslide risk. Applications open ahead of the March rains.',
    districts: ['Mbale', 'Bududa', 'Kapchorwa'],
    speciesIds: ['grevillea', 'mukebu', 'prunus'],
    maxPerApplicant: 150,
    totalSeedlings: 25000,
    seedlingsClaimed: 0,
    requirements: [
      'Farm on a slope in one of the listed districts',
      'Willing to plant along contours with support from an extension worker',
    ],
    deadline: '2027-02-28',
    status: 'Opening soon',
    collectionNurseryIds: ['elgon-shade'],
  },
];
