import { TreeSpecies } from './types.js';

export const TREE_SPECIES: TreeSpecies[] = [
  {
    id: 'mvule',
    commonName: 'Mvule',
    botanicalName: 'Milicia excelsa',
    localNames: [{ language: 'Luganda', name: 'Muvule' }],
    category: 'Indigenous timber',
    isNative: true,
    description: 'One of Uganda’s most valued hardwoods, prized for durable, termite-resistant timber. Mature trees are protected, so planting new ones is the only sustainable source.',
    uses: ['Furniture and construction timber', 'Shade on farms and compounds', 'Boundary and landmark trees'],
    regions: ['Central', 'Eastern', 'Northern', 'Western'],
    altitudeM: [0, 1500],
    growthRate: 'Slow',
    timeToHarvest: 'Timber from 40 years',
    plantingTip: 'Space at least 10 m apart and protect young trees from goats and cattle for the first two years.',
    image: 'sp-mvule',
  },
  {
    id: 'musizi',
    commonName: 'Musizi',
    botanicalName: 'Maesopsis eminii',
    localNames: [{ language: 'Luganda', name: 'Musizi' }],
    category: 'Indigenous timber',
    isNative: true,
    description: 'A fast-growing native tree widely planted for timber and as shade in coffee and banana gardens across central and western Uganda.',
    uses: ['Light construction timber', 'Shade for coffee and bananas', 'Firewood from prunings'],
    regions: ['Central', 'Western', 'Eastern'],
    altitudeM: [700, 1500],
    growthRate: 'Fast',
    timeToHarvest: 'Timber from 15–20 years',
    plantingTip: 'Needs good rainfall. Plant at 5 m × 5 m for timber or wider among crops for shade.',
    image: 'sp-musizi',
  },
  {
    id: 'nsambya',
    commonName: 'Nsambya',
    botanicalName: 'Markhamia lutea',
    localNames: [{ language: 'Luganda', name: 'Nsambya' }],
    category: 'Shade & agroforestry',
    isNative: true,
    description: 'A straight, narrow-crowned native tree common around homesteads. It casts light shade, so crops grow well beneath it.',
    uses: ['Poles and tool handles', 'Firewood', 'Boundary and windbreak planting'],
    regions: ['Central', 'Eastern', 'Western'],
    altitudeM: [900, 2000],
    growthRate: 'Moderate',
    timeToHarvest: 'Poles from 6–8 years',
    plantingTip: 'Ideal along farm boundaries at 3–4 m spacing. Coppices well after cutting.',
    image: 'sp-nsambya',
  },
  {
    id: 'mahogany',
    commonName: 'African mahogany',
    botanicalName: 'Khaya anthotheca',
    localNames: [],
    category: 'Indigenous timber',
    isNative: true,
    description: 'A large native hardwood of the Budongo and Bugoma forests, heavily logged in the past. Planting it helps restore forest edges and river banks.',
    uses: ['High-value furniture timber', 'Forest restoration', 'Riverbank planting'],
    regions: ['Western', 'Central'],
    altitudeM: [600, 1500],
    growthRate: 'Slow',
    timeToHarvest: 'Timber from 40 years',
    plantingTip: 'Grows best in moist, deep soils. Plant in partial shade among other trees rather than in open fields.',
    image: 'sp-mahogany',
  },
  {
    id: 'prunus',
    commonName: 'African cherry',
    botanicalName: 'Prunus africana',
    localNames: [],
    category: 'Medicinal & cultural',
    isNative: true,
    description: 'A highland tree whose bark is used in medicine. Wild trees are over-harvested, so it is listed for protection and farm-grown trees are in demand.',
    uses: ['Medicinal bark', 'Soil protection on steep slopes', 'Timber for tools'],
    regions: ['Western', 'Eastern'],
    altitudeM: [1500, 3000],
    growthRate: 'Moderate',
    timeToHarvest: 'Bark from about 10 years',
    plantingTip: 'Suited to highland farms such as Kigezi and Mt Elgon. Plant on contours to help hold soil.',
    image: 'sp-prunus',
  },
  {
    id: 'mutuba',
    commonName: 'Mutuba (barkcloth fig)',
    botanicalName: 'Ficus natalensis',
    localNames: [{ language: 'Luganda', name: 'Mutuba' }],
    category: 'Medicinal & cultural',
    isNative: true,
    description: 'The tree behind Ugandan barkcloth, recognised by UNESCO as intangible cultural heritage. Also planted to mark boundaries and shade coffee.',
    uses: ['Barkcloth (olubugo)', 'Coffee and banana shade', 'Live fences and boundary marking'],
    regions: ['Central', 'Western'],
    altitudeM: [900, 1800],
    growthRate: 'Fast',
    timeToHarvest: 'Bark from 3–4 years',
    plantingTip: 'Usually grown from large cuttings. Plant them at the start of the rains so they root quickly.',
    image: 'sp-mutuba',
  },
  {
    id: 'mukebu',
    commonName: 'Mukebu',
    botanicalName: 'Cordia africana',
    localNames: [{ language: 'Luganda', name: 'Mukebu' }],
    category: 'Shade & agroforestry',
    isNative: true,
    description: 'A native tree with attractive, easily worked timber and white flowers loved by bees. Common as shade in coffee farms.',
    uses: ['Furniture and drum making', 'Bee forage', 'Coffee shade'],
    regions: ['Central', 'Eastern', 'Western'],
    altitudeM: [900, 2000],
    growthRate: 'Moderate',
    timeToHarvest: 'Timber from 15 years',
    plantingTip: 'Plant 8–10 m apart among coffee. Prune lower branches to keep a clean trunk.',
    image: 'sp-mukebu',
  },
  {
    id: 'eucalyptus',
    commonName: 'Eucalyptus',
    botanicalName: 'Eucalyptus grandis',
    localNames: [{ language: 'Luganda', name: 'Kalitunsi' }],
    category: 'Fast-growing timber',
    isNative: false,
    description: 'The most widely planted woodlot tree in Uganda, grown for poles, firewood and charcoal. Fast returns, but it uses a lot of water.',
    uses: ['Building and transmission poles', 'Firewood and charcoal', 'Woodlots for income'],
    regions: ['Central', 'Eastern', 'Northern', 'Western'],
    altitudeM: [900, 2200],
    growthRate: 'Fast',
    timeToHarvest: 'Poles from 5–8 years',
    plantingTip: 'Keep woodlots well away from wetlands, springs and food gardens because roots compete strongly for water.',
    image: 'sp-eucalyptus',
  },
  {
    id: 'pine',
    commonName: 'Caribbean pine',
    botanicalName: 'Pinus caribaea',
    localNames: [],
    category: 'Fast-growing timber',
    isNative: false,
    description: 'The main softwood of Uganda’s commercial plantations, grown for sawn timber and poles.',
    uses: ['Sawn timber', 'Poles', 'Commercial plantations'],
    regions: ['Central', 'Northern', 'Western'],
    altitudeM: [600, 1500],
    growthRate: 'Fast',
    timeToHarvest: 'Timber from 18–25 years',
    plantingTip: 'Plant at 2.7 m × 2.7 m for plantations. Create fire breaks around the plot before the dry season.',
    image: 'sp-pine',
  },
  {
    id: 'grevillea',
    commonName: 'Grevillea',
    botanicalName: 'Grevillea robusta',
    localNames: [],
    category: 'Shade & agroforestry',
    isNative: false,
    description: 'A popular farm tree in highland areas. Deep roots mean it competes little with crops, and it can be pruned for firewood.',
    uses: ['Coffee and tea shade', 'Firewood from pruning', 'Boundary and contour planting'],
    regions: ['Eastern', 'Western', 'Central'],
    altitudeM: [1000, 2500],
    growthRate: 'Fast',
    timeToHarvest: 'Poles from 8–10 years',
    plantingTip: 'Plant along boundaries or contours at 4–5 m spacing and prune side branches every year.',
    image: 'sp-grevillea',
  },
  {
    id: 'jackfruit',
    commonName: 'Jackfruit',
    botanicalName: 'Artocarpus heterophyllus',
    localNames: [{ language: 'Luganda', name: 'Ffene' }],
    category: 'Fruit tree',
    isNative: false,
    description: 'A familiar homestead fruit tree that produces large fruits sold in every market, plus shade and timber.',
    uses: ['Fruit for home and market', 'Shade', 'Timber when old'],
    regions: ['Central', 'Eastern', 'Northern', 'Western'],
    altitudeM: [0, 1600],
    growthRate: 'Moderate',
    timeToHarvest: 'Fruit from 3–5 years',
    plantingTip: 'Give it space, at least 8 m from buildings, and water through the first dry season.',
    image: 'sp-jackfruit',
  },
  {
    id: 'avocado',
    commonName: 'Hass avocado (grafted)',
    botanicalName: 'Persea americana',
    localNames: [{ language: 'Luganda', name: 'Ovakedo' }],
    category: 'Fruit tree',
    isNative: false,
    description: 'Grafted Hass avocado fruits early and is in demand by exporters and local buyers alike.',
    uses: ['Fruit for export and local markets', 'Household nutrition'],
    regions: ['Central', 'Eastern', 'Western'],
    altitudeM: [1000, 2200],
    growthRate: 'Moderate',
    timeToHarvest: 'Fruit from 2–3 years',
    plantingTip: 'Buy grafted seedlings from certified nurseries. Plant 6–8 m apart in well-drained soil; avocado does not tolerate waterlogging.',
    image: 'sp-avocado',
  },
  {
    id: 'mango',
    commonName: 'Mango (grafted)',
    botanicalName: 'Mangifera indica',
    localNames: [{ language: 'Luganda', name: 'Muyembe' }],
    category: 'Fruit tree',
    isNative: false,
    description: 'Grafted varieties such as Kent and Tommy Atkins fruit sooner and more evenly than local mango, especially in Teso, Lango and West Nile.',
    uses: ['Fruit for market and juice processing', 'Shade'],
    regions: ['Northern', 'Eastern', 'Central'],
    altitudeM: [0, 1500],
    growthRate: 'Moderate',
    timeToHarvest: 'Fruit from 3–4 years',
    plantingTip: 'Plant 8–10 m apart. Remove the first flowers so the young tree puts energy into growth.',
    image: 'sp-mango',
  },
  {
    id: 'shea',
    commonName: 'Shea tree',
    botanicalName: 'Vitellaria paradoxa',
    localNames: [],
    category: 'Medicinal & cultural',
    isNative: true,
    description: 'A native tree of northern Uganda whose nuts are processed into shea butter, an important income source for women. Heavily cut for charcoal.',
    uses: ['Shea butter and oil', 'Income for women’s groups', 'Restoring savanna woodland'],
    regions: ['Northern'],
    altitudeM: [600, 1300],
    growthRate: 'Slow',
    timeToHarvest: 'Nuts from 10–15 years',
    plantingTip: 'Protect seedlings from bush fires in the dry season with a cleared ring around each tree.',
    image: 'sp-shea',
  },
];

