/**
 * Every user-facing string on the public site, in one place so a Luganda version can be added
 * later. Plain, active wording; an action keeps the same name throughout its flow.
 */
import type { ApplicationStatus, CertificationStatus, FunderType, GrowthPace, NewsCategory, NurseryType, PaymentMethod, SpeciesCategory } from '@nurserylink/shared';

export const en = {
  app: {
    name: 'Nursery Link',
    fullName: 'Nursery Link Uganda',
    skipToContent: 'Skip to main content',
    menu: 'Menu',
    closeMenu: 'Close menu',
    dismiss: 'Dismiss',
    home: 'Home',
  },
  nav: {
    nurseries: 'Find nurseries',
    freeSeedlings: 'Free seedlings',
    library: 'Tree library',
    news: 'News & advice',
    orders: 'My orders',
    signIn: 'Sign in',
    signOut: 'Sign out',
    account: 'Account',
  },
  footer: {
    tagline: 'Your trusted link to quality seedlings, connecting tree planters with nurseries across Uganda.',
    explore: 'Explore',
    about: 'About',
    country: 'Uganda',
    credits: 'Credits',
    mapData: 'Map data © OpenStreetMap contributors',
    pilot: 'Pilot: Mukono District',
  },
  offline: {
    banner: "You're offline. You can still browse pages you've opened before.",
    cachedNote: (when: string) => `Offline · Last updated ${when}`,
    cachedNoteUnknown: 'Offline · Showing the copy saved on your phone',
    updateReady: 'A new version of Nursery Link is ready.',
  },
  states: {
    loadFailed: "We couldn't load this page.",
    loadFailedHelp: 'Check your connection and try again.',
    offlineNoCache: "You're offline and this page hasn't been saved on your phone yet.",
    retry: 'Try again',
    goHome: 'Go to the home page',
  },
  notFound: {
    title: "We can't find that page",
    body: 'The link may be old or mistyped. Try finding nurseries, or go back to the home page.',
    findNurseries: 'Find nurseries',
  },
  routeError: {
    title: 'Something went wrong on this page',
    body: 'The rest of Nursery Link still works. Try again, or go back to the home page.',
  },
  auth: {
    panel: {
      title: 'Plant the right tree, from a nursery near you.',
      points: ['Order seedlings and pay with mobile money', 'Apply for free-seedling campaigns', 'Follow your orders by SMS'],
      pointsTrial: ['Order seedlings online', 'Apply for free-seedling campaigns', 'Follow your orders by SMS'],
    },
    phoneLabel: 'Phone number',
    phoneHint: 'Your MTN or Airtel number, e.g. 0772 123 456',
    passwordLabel: 'Password',
    passwordHint: 'At least 8 characters',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    register: {
      title: 'Create your account',
      intro: 'You need an account to order seedlings and apply for free seedlings.',
      nameLabel: 'Full name',
      emailLabel: 'Email (optional)',
      emailHint: 'Only used to reset your password if you lose your phone.',
      submit: 'Create account',
      haveAccount: 'Already have an account?',
      signInLink: 'Sign in',
      welcome: (name: string) => `Welcome, ${name}`,
    },
    verify: {
      title: 'Enter the code we sent you',
      intro: (phone: string) => `We sent a 6-digit code by SMS to ${phone}. It expires in 10 minutes.`,
      codeLabel: 'Verification code',
      submit: 'Confirm my number',
      resend: 'Send a new code',
      resendIn: (s: number) => `Send a new code in ${String(s)} s`,
      resent: 'A new code is on its way.',
      wrongNumber: 'Wrong number? Start again',
      verified: 'Your number is confirmed. Welcome!',
    },
    login: {
      title: 'Sign in',
      identifierLabel: 'Phone number or email',
      identifierHint: 'e.g. 0772 123 456',
      submit: 'Sign in',
      forgot: 'Forgot your password?',
      noAccount: 'New to Nursery Link?',
      registerLink: 'Create an account',
      notVerified: 'Please confirm your phone number first. We have sent you a new code.',
      welcomeBack: (name: string) => `Welcome back, ${name}`,
    },
    forgot: {
      title: 'Reset your password',
      intro: 'Enter your phone number to get a code by SMS, or your email to get a reset link.',
      identifierLabel: 'Phone number or email',
      submit: 'Send reset code',
      sentEmail: 'If an account uses that email, a reset link is on its way. It works for 30 minutes.',
    },
    reset: {
      title: 'Choose a new password',
      codeIntro: (phone: string) => `Enter the code we sent to ${phone}, then your new password.`,
      linkIntro: 'Choose a new password for your account.',
      newPasswordLabel: 'New password',
      submit: 'Save new password',
      done: 'Your password has been changed. Please sign in.',
    },
    signedOut: "You're signed out.",
    signInToContinue: 'Please sign in to continue.',
  },
  credits: {
    title: 'Credits',
    dataHeading: 'Maps and data',
    data: [
      {
        name: 'District and sub-county boundaries',
        by: 'Uganda Bureau of Statistics (UBOS), published by UN OCHA on the Humanitarian Data Exchange (2020; simplified for the web)',
        license: 'CC BY-IGO 3.0',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0/igo/',
        source: 'https://data.humdata.org/dataset/cod-ab-uga',
      },
      {
        name: 'MTN and Airtel logos',
        by: 'Trademarks of MTN Group and Airtel Africa, shown to name the mobile money services we take. Files from Wikimedia Commons',
        license: 'Public domain (text logos)',
        licenseUrl: 'https://commons.wikimedia.org/wiki/File:MTN_2022_logo.svg',
        source: 'https://commons.wikimedia.org/wiki/File:Airtel_logo.svg',
      },
      {
        name: 'Map tiles and place search',
        by: 'OpenStreetMap contributors',
        license: 'ODbL',
        licenseUrl: 'https://www.openstreetmap.org/copyright',
        source: 'https://www.openstreetmap.org',
      },
    ],
    photosHeading: 'Photos',
    intro: 'Photos are from Wikimedia Commons and are used under their Creative Commons licences.',
    by: 'Photo by',
    source: 'Source',
    changed: (what: string) => `Changes: ${what}`,
  },
  checkout: {
    title: (nursery: string) => `Order from ${nursery}`,
    back: 'Back to the nursery',
    steps: { seedlings: 'Seedlings', delivery: 'Delivery', pay: 'Pay' },
    stepOf: (n: number, total: number) => `Step ${String(n)} of ${String(total)}`,
    seedlingsHeading: 'How many seedlings?',
    each: 'each',
    chooseSome: 'Choose at least one tree to order.',
    subtotal: 'Seedlings',
    next: 'Next',
    backStep: 'Back',
    deliveryHeading: 'How will you get them?',
    deliver: 'Deliver to me',
    deliverHint: 'A boda boda or truck brings them; the fee depends on road distance.',
    collect: "I'll collect",
    collectHint: 'Pick them up at the nursery. No delivery fee.',
    pinLabel: 'Delivery point',
    pinHelp: 'Type a nearby place, use your location, or tap the map where the seedlings should be dropped. Then drag the pin to the exact spot.',
    useMyLocation: 'Use my location',
    findPlace: 'Find the delivery place by name',
    pinMissing: 'Choose the delivery point on the map.',
    addressLabel: 'Address or landmark',
    addressHint: 'Village, road, or a landmark the rider can ask for, e.g. "Behind Seeta market, blue gate".',
    addressMissing: 'Tell the rider where to come (at least 5 letters).',
    collectFrom: (place: string) => `Collect from ${place}.`,
    quoteHeading: 'Your quote',
    quoteLoading: 'Working out your price…',
    quoteExpires: (time: string) => `Price held for ${time}`,
    quoteRefreshed: 'Your quote was refreshed.',
    deliveryLine: (km: string) => `Delivery · ${km}`,
    pickupLine: 'Collection at the nursery',
    free: 'Free',
    total: 'Total',
    payWith: 'Pay with',
    methods: { mtn_momo: 'MTN MoMo', airtel_money: 'Airtel Money', trial: 'No payment (trial)' } satisfies Record<PaymentMethod, string>,
    trialHeading: 'No payment needed',
    trialNote: 'Payments are switched off while we test the service. Your order is confirmed straight away and nothing is charged.',
    placeOrder: (total: string) => `Place order · ${total}`,
    methodHint: 'Approve the payment on your phone',
    methodUnavailable: 'Not available yet',
    chooseMethod: 'Choose how you will pay.',
    payerLabel: 'Paying phone number',
    payerHint: 'The mobile money number that will approve the payment.',
    wrongNetwork: (network: string) => `This looks like an ${network} number. Choose ${network} to pay with it.`,
    pay: (amount: string) => `Pay ${amount}`,
    changedTitle: 'Some things changed since your quote',
    changedPrice: (name: string, from: string, to: string) => `${name}: price changed from ${from} to ${to}.`,
    changedStock: (name: string, n: string) => `${name}: only ${n} left. We have lowered your quantity.`,
    changedGone: (name: string) => `${name}: no longer available. We removed it.`,
    requoted: 'Check your new quote below, then pay.',
    tooFar: 'This place is too far for our riders. Choose a closer point, or collect from the nursery.',
    tooMany: 'This order is too big to deliver in one trip. Order fewer seedlings, or collect from the nursery.',
    quoteFailed: "We couldn't work out a price right now.",
    payFailed: "We couldn't start the payment. Nothing has been charged.",
  },
  order: {
    myOrders: 'My orders',
    myOrdersIntro: 'Follow your orders and confirm when the seedlings arrive.',
    noOrders: 'You have no orders yet',
    noOrdersBody: 'Find a nursery near you and order seedlings for delivery or collection.',
    findNurseries: 'Find nurseries',
    loadFailed: "We couldn't load your orders",
    orderTitle: (code: string) => `Order ${code}`,
    placedOn: (when: string) => `Ordered ${when}`,
    from: (nursery: string) => `From ${nursery}`,
    waitingTitle: 'Check your phone and approve the payment',
    waitingBody: (amount: string, phone: string) => `We sent a request for ${amount} to ${phone}. Enter your mobile money PIN when the prompt appears.`,
    waitingSlow: "No prompt yet? It can take a minute. If it doesn't come, open your mobile money menu and look for payments waiting for approval.",
    waitingExpiry: 'If the payment is not approved within 15 minutes, the order is cancelled and nothing is charged.',
    paidTitle: 'Order placed',
    failedTitle: "The payment didn't go through",
    failedBody: 'Nothing was charged, and the seedlings have been released. You can try again.',
    tryAgain: 'Try again',
    nextHeading: 'What happens next',
    nextSteps: {
      deliver: ['The nursery has your order by SMS and prepares your seedlings.', 'We text you when they are on the way.', 'Check the seedlings when they arrive, then confirm delivery here.'],
      collect: ['The nursery has your order by SMS and prepares your seedlings.', 'We text you when they are ready to collect.', 'Check the seedlings when you collect them, then confirm here.'],
    },
    escrowNote: 'Your money is held safely by Nursery Link and only paid to the nursery after you confirm.',
    items: 'Seedlings',
    deliveryTo: 'Delivery to',
    collectAt: 'Collect at',
    paidWith: (method: string, phone: string) => `Paid with ${method} from ${phone}`,
    requestedFrom: (method: string, phone: string) => `${method} payment requested from ${phone}`,
    call: (nursery: string) => `Call ${nursery}`,
    confirm: 'Confirm delivery',
    confirmTitle: 'Did your seedlings arrive in good condition?',
    confirmBody: (amount: string, nursery: string) => `Confirming releases ${amount} to ${nursery}. Only confirm once you have checked the seedlings.`,
    confirmYes: 'Yes, confirm delivery',
    confirmNo: 'Not yet',
    confirmed: 'Thank you. The nursery is being paid.',
    autoConfirm: (when: string) => `If you don't confirm, we confirm automatically on ${when} (72 hours after dispatch) and pay the nursery. Something wrong? Call the nursery or reply to our SMS before then.`,
    timelineHeading: 'Progress',
    statusLabel: 'Status',
    olderOrders: 'Older orders',
    newerOrders: 'Newer orders',
  },
  orderStatus: {
    pending_payment: 'Waiting for your payment',
    escrow_held: 'Paid — nursery notified',
    dispatched: 'On the way',
    dispatched_pickup: 'Ready to collect',
    delivered: 'Delivered — paying the nursery',
    released: 'Completed',
    disputed: 'Problem reported — our team is helping',
    refunded: 'Refunded',
    cancelled: 'Cancelled — payment not completed',
  },
  /** Trial orders (payments switched off): confirmed without paying */
  orderStatusTrial: {
    escrow_held: 'Confirmed — nursery notified',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
  },
  timeline: {
    ordered: 'Ordered',
    paid: 'Paid',
    confirmed: 'Confirmed',
    dispatched: 'On the way',
    dispatched_pickup: 'Ready',
    delivered: 'Delivered',
    completed: 'Completed',
  },
  freeSeedlings: {
    title: 'Free seedlings',
    intro: 'Government, NGO and company campaigns giving free seedlings to people who meet their conditions. Apply here, then collect from the pickup nursery.',
    subCounty: 'Sub-county',
    allSubCounties: 'All sub-counties',
    purposeLabel: 'What for',
    purposePlaceholder: 'e.g. shoreline, coffee shade, woodlot',
    count: (n: number) => (n === 1 ? '1 campaign running' : `${String(n)} campaigns running`),
    emptyTitle: 'No campaigns match',
    emptyBody: 'Try another sub-county, or clear the search. New campaigns are added often.',
    loadFailed: "We couldn't load the campaigns",
    funder: { government: 'Government', ngo: 'NGO', foundation: 'Foundation', corporate: 'Company' } satisfies Record<FunderType, string>,
    fundedBy: (name: string) => `Funded by ${name}`,
    closes: (date: string) => `Apply by ${date}`,
    closed: 'This campaign has closed',
    closedBody: 'It is no longer taking applications. See the campaigns running now.',
    seeRunning: 'See running campaigns',
    left: (n: string, pct: number) => `${n} seedlings left (${String(pct)}%)`,
    trees: 'Trees on offer',
    pickupHeading: 'Where to collect',
    pickupAt: (nursery: string, place: string) => `${nursery}, ${place}`,
    back: 'All free-seedling campaigns',
    eligibilityHeading: 'Who can apply',
    eligibilityIntro: 'Answer honestly: the funder checks your answers before approving.',
    required: 'required',
    optional: 'optional',
    yes: 'Yes, this is true for me',
    quantityLabel: 'How many seedlings do you need?',
    quantityHint: (max: string) => `Up to ${max}. Ask only for what you can plant and care for.`,
    quantityInvalid: (max: string) => `Enter a number from 1 to ${max}.`,
    apply: 'Apply for free seedlings',
    signInToApply: 'Sign in to apply',
    signInHint: 'You need an account so the funder can contact you by SMS.',
    applied: 'Application sent',
    statusHeading: 'Your application',
    status: {
      pending: 'Application received — waiting for review',
      approved: 'Approved — collect your seedlings',
      rejected: 'Not approved this time',
      collected: 'Collected',
    } satisfies Record<ApplicationStatus, string>,
    statusHelp: {
      pending: 'We will text you when the funder has decided.',
      approved: 'Bring the approval SMS to the pickup nursery.',
      rejected: 'You can apply to other campaigns.',
      collected: 'Thank you for planting.',
    } satisfies Record<ApplicationStatus, string>,
    requested: (n: string) => `${n} seedlings requested`,
  },
  orderMap: {
    title: (code: string) => `Order ${code}`,
    intro: 'Where to bring this order, and who to call.',
    deliverTo: 'Deliver to',
    collect: 'The buyer will collect from your nursery.',
    buyer: 'Buyer',
    call: 'Call the buyer',
    items: 'Seedlings to prepare',
    directions: 'Open directions in maps',
    notFound: "This link doesn't open an order. Check the full link in the SMS.",
    replyHint: (code: string) => `When the seedlings leave, reply to the SMS: ${code} 1. If you can't supply them: ${code} 2.`,
  },
  payments: {
    methodsLabel: 'Mobile money services',
    comingSoon: 'Mobile money payments coming soon',
    payWith: 'Pay with mobile money',
  },
  home: {
    eyebrow: 'Tree nurseries across Uganda',
    title: 'Tree seedlings from nurseries',
    titleAccent: 'near you',
    lead: 'See what local nurseries have in stock and what it costs, then collect your seedlings or get them brought by boda boda.',
    searchLabel: 'Search a tree or nursery',
    searchPlaceholder: 'Try Mvule, mango, avocado…',
    search: 'Search',
    useLocation: 'Use my location',
    popular: 'Popular:',
    popularTrees: ['Mvule', 'Mango', 'Avocado', 'Musizi', 'Grevillea'],
    modulesHeading: 'What do you need?',
    modules: {
      nurseries: 'Find nurseries',
      nurseriesHint: 'Map, stock and prices near you',
      free: 'Free seedlings',
      freeHint: 'Campaigns you can apply to',
      library: 'Tree library',
      libraryHint: 'Which tree suits your land',
      news: 'News & advice',
      newsHint: 'Rains, prices and grants',
    },
    stepsHeading: 'Seedlings to your garden in three steps',
    steps: [
      { title: 'Find a nursery', body: 'Search a tree and see which nurseries near you have it, how many, and the price per seedling.' },
      { title: 'Pay with mobile money', body: 'MTN MoMo or Airtel Money. We hold your money safely until the seedlings reach you.' },
      { title: 'Collect or get them delivered', body: 'Pick them up at the nursery, or a boda boda brings them. Confirm they arrived and the nursery is paid.' },
    ],
    /** Step 2 while payments are switched off (trial) */
    stepTrial: { title: 'Place your order', body: 'The nursery is told straight away. Nothing to pay while we test the service.' },
    stepsPhotoAlt: 'People unloading young tree seedlings from a truck',
    stepsPhotoCaption: 'Seedlings arriving by truck',
    stepsCta: 'Find a nursery',
    freeBadge: 'Free',
    campaignsHeading: 'Free seedlings near you',
    campaignsHeadingAll: 'Free seedlings now',
    campaignsEmpty: 'No free-seedling campaigns are running right now. Check again soon.',
    seeAll: 'See all',
    left: (pct: number) => `${String(pct)}% left`,
    pickup: (place: string) => `Collect at ${place}`,
    newsHeading: 'Latest advice',
    newsEmpty: 'No advice posted yet.',
  },
  library: {
    title: 'Tree library',
    intro: 'Learn what each tree needs before you buy: how fast it grows, how big it gets, and where it does well.',
    filterLabel: 'Show',
    all: 'All trees',
    jumpTo: 'Jump to letter',
    searchLabel: 'Search the library',
    searchPlaceholder: 'Tree name, e.g. Mvule or Milicia',
    count: (n: number) => (n === 1 ? '1 tree' : `${String(n)} trees`),
    atNurseries: (n: number) => (n === 0 ? 'Not in stock now' : n === 1 ? 'At 1 nursery' : `At ${String(n)} nurseries`),
    emptyTitle: 'No trees match',
    emptyBody: 'Try another name, or show all trees.',
    loadFailed: "We couldn't load the tree library",
  },
  species: {
    back: 'Tree library',
    alsoCalled: 'Local names',
    findNearMe: 'Find nurseries near me',
    availability: (n: number, from: string | null, to: string | null) =>
      n === 0 ? 'No nursery lists this tree right now.' : `In stock at ${n === 1 ? '1 nursery' : `${String(n)} nurseries`}${from ? `, ${from === to ? from : `${from}–${to ?? ''}`} each` : ''}.`,
    priceGuide: 'Price guide',
    nfaPrice: (price: string, inches: number) => `${price} a seedling at the National Forestry Authority (${String(inches)}-inch pot, January 2024).`,
    priceGuideMore: 'More on seedling prices',
    growthHeading: 'Growth over the years',
    growthCaption: 'Typical height in good conditions. Growth is slower on poor or dry soils.',
    yearsLabel: (n: number) => (n === 1 ? '1 year' : `${String(n)} years`),
    metres: (m: number) => `${String(m)} m`,
    heightAt: (years: number, m: number) => `${years === 1 ? '1 year' : `${String(years)} years`}: about ${String(m)} m tall`,
    specimenHeading: 'Specimen notes',
    canopy: 'Canopy',
    roots: 'Roots',
    zonesHeading: 'Where it grows well',
    photos: 'Photos',
    notFound: "We don't have that tree in the library",
    loadFailed: "We couldn't load this tree",
  },
  news: {
    title: 'News & advice',
    intro: 'Weather warnings, seedling prices, and policy and grant news for tree planters.',
    all: 'All',
    categories: { weather: 'Weather', market: 'Market prices', policy: 'Policy', grant: 'Grants' } satisfies Record<NewsCategory, string>,
    readMore: 'Read',
    back: 'All news',
    emptyTitle: 'Nothing posted here yet',
    emptyBody: 'Check back soon, or look at another category.',
    loadFailed: "We couldn't load the news",
    notFound: "We can't find that article",
    older: 'Older posts',
    newer: 'Newer posts',
    page: (n: number, of: number) => `Page ${String(n)} of ${String(of)}`,
    latest: 'Latest',
    readingTime: (min: number) => `${String(min)} min read`,
    more: 'More advice',
    calendar: {
      heading: 'Planting calendar',
      intro: 'Mukono has two rainy seasons a year. Plant in the rains, so young roots settle before the dry months.',
      monthsLabel: 'Seasons month by month',
      now: (month: string) => `Now: ${month}`,
      seasons: { rains: 'Planting season', prep: 'Get ready', dry: 'Dry season' },
      todo: {
        rains: 'Plant once the ground is soaked through. Order seedlings now if you haven’t yet.',
        prep: 'The rains are coming. Order seedlings two to four weeks ahead and dig the planting holes.',
        dry: 'Water young trees early or late in the day, mulch around them, and keep goats and cattle away.',
      },
    },
    links: {
      heading: 'Get planting',
      nurseries: 'Find seedlings near you',
      free: 'Free seedlings',
      library: 'Which tree should I plant?',
    },
    nextStep: {
      weather: { title: 'Ready to plant?', body: 'Find a nursery near you with the trees you want in stock, and have them delivered by boda boda.', cta: 'Find nurseries' },
      market: { title: 'Compare prices yourself', body: 'Every nursery lists its trees and prices, so you can see who has the best deal near you.', cta: 'Find nurseries' },
      policy: { title: 'Choose the right tree', body: 'The tree library shows where each tree grows well, how fast it grows and what it is good for.', cta: 'Open the tree library' },
      grant: { title: 'Free seedlings', body: 'See which giveaways are open near you and check whether you qualify.', cta: 'See free seedlings' },
    } satisfies Record<NewsCategory, { title: string; body: string; cta: string }>,
  },
  nurseries: {
    clusterLabel: (count: number, gift: boolean) => `${String(count)} nurseries here${gift ? ', some with free seedlings' : ''}. Zoom in`,
    title: 'Find nurseries',
    searchLabel: 'Search a tree or nursery',
    searchPlaceholder: 'e.g. Mvule, mango, Katosi',
    clearSearch: 'Clear search',
    district: 'District',
    subCounty: 'Sub-county',
    allDistricts: 'All districts',
    allSubCounties: 'All sub-counties',
    chooseDistrictFirst: 'Pick district',
    sortNearest: 'Sort by nearest',
    sortedByRoad: 'Nearest first, by road distance',
    sortedStraight: 'Nearest first (approx. distances: road routing unavailable)',
    count: (n: number) => (n === 1 ? '1 nursery' : `${String(n)} nurseries`),
    nearestCount: (n: number) => `${String(n)} nearest nurseries`,
    viewMap: 'Map',
    viewList: 'List',
    viewToggle: 'Show as',
    emptyTitle: 'No nurseries match',
    emptyBody: 'Try a different tree name, or choose “All districts”.',
    clearFilters: 'Clear filters',
    loadFailed: "We couldn't load nurseries",
    freeSeedlings: 'Free seedlings here',
    speciesCount: (n: number) => (n === 1 ? '1 kind of tree' : `${String(n)} kinds of trees`),
    sample: 'Sample',
    filterSpecies: (name: string) => `Stocking “${name}”`,
    removeSpecies: 'Show all nurseries',
    mapLabel: 'Map of nurseries',
    showList: 'Show list',
    locateMe: 'Show my location',
    expandList: 'Show more of the list',
    collapseList: 'Show more of the map',
  },
  search: {
    count: (n: number) => (n === 1 ? '1 suggestion. Use up and down to choose.' : `${String(n)} suggestions. Use up and down to choose.`),
    listLabel: 'Suggestions',
    kinds: { species: 'Tree', nursery: 'Nursery', place: 'Place' },
    levels: { district: 'District', sub_county: 'Sub-county' },
    alsoCalled: (name: string) => `Also called ${name}`,
    atNurseries: (n: number) => (n === 0 ? 'Not in stock now' : n === 1 ? 'At 1 nursery' : `At ${String(n)} nurseries`),
    inDistrict: (district: string) => `${district} District`,
    showingFor: 'Showing results for',
    noExactMatch: (q: string) => `No exact match for “${q}”.`,
  },
  places: {
    label: 'Type a place',
    placeholder: 'Town, village, school or landmark',
    search: 'Search',
    searching: 'Searching…',
    pressSearch: 'Press Search to look up villages and landmarks too.',
    none: (q: string) => `We couldn’t find “${q}”. Try a nearby town or trading centre, or tap the map.`,
    failed: 'Place search isn’t working right now. Tap the map instead.',
    osmDown: 'Village and landmark search is unavailable right now; showing districts and sub-counties only.',
    osmCredit: 'Places from OpenStreetMap',
  },
  location: {
    askTitle: 'Use your location?',
    askBody: 'We use it only to sort nurseries by road distance from you and to draw directions. It stays on your phone and is not saved.',
    allow: 'Use my location',
    notNow: 'Not now',
    denied: 'Location is off, so we can’t sort by distance. You can still choose your district.',
    unavailable: 'We couldn’t find your location. Check that location (GPS) is on, or choose your district.',
    finding: 'Finding your location…',
    typeInstead: 'Or type where you are',
  },
  nurseryCard: {
    close: 'Close nursery details',
    sampleTitle: 'Sample nursery',
    sampleBody: 'Invented for testing the site. It isn’t a real nursery, so don’t travel there or expect a call.',
    noPhone: 'no phone number',
    certification: { certified: 'Certified', pending: 'Certification pending', unverified: 'Not yet certified' } satisfies Record<CertificationStatus, string>,
    types: { community: 'Community nursery', commercial: 'Commercial nursery', private: 'Private nursery' } satisfies Record<NurseryType, string>,
    capacity: (n: string) => `Grows up to ${n} seedlings a year`,
    seedSource: 'Seed source',
    call: 'Call',
    stocks: 'Trees in stock',
    stockUpdated: (when: string) => `Stock updated ${when}`,
    stockStale: (when: string) => `Stock updated ${when}: call to check before you travel`,
    stockUnknown: 'No stock listed yet',
    inStock: 'In stock',
    each: 'each',
    available: (n: string) => `${n} available`,
    aboutTree: (name: string) => `About ${name}`,
    directions: 'Get directions',
    order: 'Order & deliver',
    freeCampaigns: 'Free seedlings from this nursery',
    seeCampaign: 'See how to apply',
    loadFailed: "We couldn't load this nursery",
    distanceFromYou: (d: string) => `${d} from you`,
  },
  directions: {
    title: (name: string) => `Directions to ${name}`,
    summary: (km: string, min: number) => `${km} · about ${String(min)} min by car`,
    back: 'Back to nursery',
    failed: 'We couldn’t work out a road route right now. Try again in a moment.',
    needLocation: 'Directions start from where you are, so we need your location.',
    steps: 'Steps',
  },
  speciesDrawer: {
    close: 'Close tree details',
    openFull: 'Open full page in the Tree library',
    growth: 'Growth',
    pace: { fast: 'Fast growing', moderate: 'Moderate growth', slow: 'Slow growing' } satisfies Record<GrowthPace, string>,
    canopy: 'Canopy',
    roots: 'Roots',
    zones: 'Where it grows',
    localNames: 'Local names',
  },
  categories: {
    indigenous: 'Indigenous',
    agroforestry: 'Agroforestry',
    exotic: 'Exotic',
    ornamental: 'Ornamental',
    medicinal: 'Medicinal',
  } satisfies Record<SpeciesCategory, string>,
} as const;
